config/routes.rb
NewIssues::Application.routes.draw do
  scope "/:locale" do
    get "timeline/index"
  
    resources :projects
  
  
    resources :issues
  end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :description, :no_followers, :title, :tags
  validates_presence_of :title
  validates_uniqueness_of :title, message: "should be unique, sir."
  
  # validates_length_of :description, minimum: 10, maximum: 12
  validates_numericality_of :no_followers, allow_blank: true
  
  validates_with Yesnovalidator
  
  belongs_to :project
  
  after_create :add_to_timeline
  
  before_save :strip_spaces_from_tags
  
  private
  
  def add_to_timeline
    Timeline.create!({ content: "An issue was created!", timelineable_id: id, timelineable_type: self.class.to_s })
  end
  
  def strip_spaces_from_tags
    self.tags.gsub! ", ", ","
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :issues
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  attr_accessible :content, :timelineable_id, :timelineable_type
  belongs_to :timelineable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_locale
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue
    @issues = Issue.order(params[:sort]) if params[:sort]
    @issues = @issues.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
      format.xml { render xml: @issues }
      format.rss # index.rss.builder
      format.csv # index.csv.erb
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        #format.html { redirect_to issue_path(id: @issue.id), notice: t('issues.created', title: @issue.title) }
        format.html { redirect_to issue_path(id: @issue.id), notice: t('issues.created', 'title: @issue.title') }
        #format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  def index
    @timelines = Timeline.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :no_followers %><br />
    <%= f.number_field :no_followers %>
  </div>
  <div class="field">
  	<%= f.label :tags %>
  	<%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/_search.html.erb
<h2>Search</h2>

<%= form_tag "/search", method: :get do %>
<p>
	<%= text_field_tag :title, nil, size: 30, placeholder: "Issue title" %>
</p>

<ul>
	<li><%=check_box_tag :followers, 1, true %>1 follower</li>
	<li><%=check_box_tag :followers, 2, true %>2 followers</li>
	<li><%=check_box_tag :followers, 3, true %>3+ followers</li>
</ul>

<p>
	<%= date_select :created_at_start, nil %>
	&rArr;
	<%= date_select :created_at_end, nil%>
</p>

<p>
	<%= submit_tag "Search issues" %>
</p>
<%-end%>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.csv.erb
<% @issues.each do |issue| %>
<%=issue.title%>,<%=issue.created_at.to_s(:rfc822)%>,<%=issue.description%>
<% end %>

app/views/issues/index.html.erb
<%- content_for :nav do %>
	<li><a href="/issues/2">First issue</a></li>
<%- end %>

<%=render "search"%>

<h1>Listing issues</h1>

<table>
  <tr>
    <th>Title <%=link_to "sort", issues_path(sort: "title")%></th>
    <th>Description <%=link_to "sort", issues_path(sort: "description")%></th>
    <th>No followers <%=link_to "sort", issues_path(sort: "no_followers")%></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.title %></td>
    <td><%= issue.description %></td>
    <td><%= issue.no_followers %></td>
    <td><%= link_to 'Show', issue_path(id: issue.id) %></td>
    <td><%= link_to 'Edit', edit_issue_path(id: issue.id) %></td>
    <td><%= link_to 'Destroy', issue_path(id: issue.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @issue.title %>
</p>

<p>
  <b>Description:</b>
  <%= @issue.description %>
</p>

<p>
  <b>No followers:</b>
  <%= @issue.no_followers %>
</p>

<p><b>Created at: </b>
	<%= l @issue.created_at, format: :short %>
</p>

<p><b>Project: </b>
	<%= link_to @issue.project.name, @issue.project %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewIssues</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag(:rss, issues_path(:rss)) %>
</head>
<body>
	<ul>
		<li><a href="/timeline/index"><%=t "nav.timeline" %></a></li>
		<li><a href="/issues"><%=t "nav.issues.list" %></a></li>
		<li><a href="/issues/new"><%=t "nav.issues.new" %></a></li>
		<%= yield :nav %>
	</ul>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<h3>List of issues for this project</h3>

<ul>
	<%- @project.issues.each do |issue| %>
		<li><%=link_to issue.title, issue %></li>
	<%- end %>
</ul>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/timeline/index.html.erb
<h1>Timeline</h1>

<table>
	<%-@timelines.each do |timeline| %>
	<tr>
		<td><%=timeline.content %></td>
		<td><%=link_to timeline.timelineable.title, timeline.timelineable %></td>
		<td><%=time_ago_in_words timeline.created_at %></td>
	</tr>
	<%-end%>
</table>